#Adapted from the app.yml file found on the github repository called nick-singh
version: '2'
services:
  app:
     image: shivendracomp6905/foodops
     ports:
       - "80:8080"
     env_file: .env
     environment:
       - DB_USER=$DB_USER
       - DB_NAME=$DB_NAME
       - DB_PASSWORD=$DB_PASS
       - DB_HOST=$DB_HOST
